apiVersion: v1
kind: Service
metadata:
  name: client-service

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: sandbox-frontend
          image: us-west1-docker.pkg.dev/sandbox-327103/sandbox-containers/sandbox_client
          ports:
              - containerPort: 80
