apiVersion: v1
kind: Service
metadata:
  name: client-service

spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: sandbox-frontend
          image: us-west1-docker.pkg.dev/algothingy-main/algothingy-containers/algothingy_frontend_sandbox
          ports:
              - containerPort: 8080
                protocol: TCP
